apiVersion: v1
metadata:
  name: kube-lego6
  namespace: kube-lego6
data:
  # modify this to specify your address
  lego.email: susi-alexa@gmail.com"
  # configure letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
kind: ConfigMap
